language: java
jdk:
- openjdk17
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
before_install:
  - sysctl vm.overcommit_memory=1
  - echo "vm.overcommit_memory=1" | sudo tee -a /etc/sysctl.conf
  - redis-server
  - openssl aes-256-cbc -K $encrypted_fed9c5fd79dc_key -iv $encrypted_fed9c5fd79dc_iv
    -in ./src/main/resources/application-yml.tar.enc -out application-yml.tar -d
  - chmod +x gradlew
script: "./gradlew clean build"
before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp src/main/resources/application-real1.yml before-deploy/
  - cp src/main/resources/application-real2.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/login-webservice.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: login-webservice-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait_until_deployed: true
  on:
    branch: main

- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: login-webservice-build
  key: login-webservice.zip
  bundle_type: zip
  application: login-webservice
  deployment_group: login-webservice-group
  region: ap-northeast-2
  wait_until_deployed: true
  on:
    branch: main

notifications:
  email:
    recipients:
    - 2tgb02023@gmail.com
