language: java
jdk:
- openjdk17
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
before_install:
  - openssl aes-256-cbc -K $encrypted_fed9c5fd79dc_key -iv $encrypted_fed9c5fd79dc_iv
    -in ./src/main/resources/application-yml.tar.enc -out application-yml.tar -d
  - chmod +x gradlew
script: "./gradlew clean build"
before_deploy:
  - zip -r login-webservice *
  - mkdir -p deploy
  - mv login-webservice.zip deploy/login-webservice.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: login-webservice-build
  region: np-northeast-2
  skip_cleanup: false
  acl: private
  local_dir: deploy
  wait-until-deployed: true
  on:
    branch: main

notifications:
  email:
    recipients:
    - 2tgb02023@gmail.com
